BootStrap: docker
From: ubuntu:22.04

%post
##############################################################################
# POST
##############################################################################

# CHANGE DASH TO BASH
rm /bin/sh
ln -sf /bin/bash /bin/sh

export DEBIAN_FRONTEND=noninteractive
export SRC_FOLDER="/usr/local/src"

# INSTALL SYSTEM DEPS
#####################
apt-get update -y && apt-get install -y cmake \
                                        g++ \
                                        gfortran \
                                        wget \
                                        tar \
                                        libsqlite3-dev \
                                        sip-dev \
                                        libtiff-dev \
                                        libfftw3-dev \
                                        libeigen3-dev \
                                        libboost-all-dev \
                                        libpng-dev \
                                        python3-pip \
                                        python3-sphinx \
                                        python3-all \
                                        python3-numpy \
                                        python3-scipy \
                                        python3-pandas \
                                        python3-matplotlib \
                                        python3-rdkit \
                                        python3-biopython \
                                        clustalw \
                                        dssp \
                                        jupyter \
                                        git \
                                        curl \
                                        locales


# INSTALL DOCKQ
###############
cd ${SRC_FOLDER} && \
git clone https://github.com/bjornwallner/DockQ.git && \
cd DockQ && make && export PATH=${SRC_FOLDER}/DockQ:${PATH}

# INSTALL OST
#############
cd ${SRC_FOLDER} && \
# copy ost release  && \
git clone https://git.scicore.unibas.ch/schwede/openstructure.git && \
cd openstructure && \
git checkout develop && \
mkdir build && \
cd build && \
cmake .. -DOPTIMIZE=ON \
         -DCOMPILE_TMTOOLS=1 \
         -DENABLE_GFX=ON \
         -DENABLE_GUI=OFF \
         -DENABLE_INFO=OFF \
         -DCMAKE_C_FLAGS="-isystem /usr/include/boost/" \
         -DCMAKE_CXX_FLAGS="-isystem /usr/include/boost/" && \
make && \
wget ftp://ftp.wwpdb.org/pub/pdb/data/monomers/components.cif.gz && \
stage/bin/chemdict_tool create components.cif.gz compounds.chemlib pdb && stage/bin/chemdict_tool update ../modules/conop/data/charmm.cif compounds.chemlib charmm && \
cmake .. -DCOMPOUND_LIB=${SRC_FOLDER}/openstructure/build/compounds.chemlib && \
         make && make check && make install

# SET LOCALE
############
echo "LC_ALL=en_US.UTF-8" >> /etc/environment
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
locale-gen en_US.UTF-8

%environment
export PATH=/usr/local/src/DockQ:$PATH
export PYTHONPATH=/usr/local/lib64/python3.10/site-packages:$PYTHONPATH
export OST_ROOT="/usr/local"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib64"

